{"name": "Получение данных о питомце по невалидному id за границами валидации", "status": "failed", "statusDetails": {"message": "AssertionError: assert 404 == 400\n +  where 404 = <Response [404]>.status_code", "trace": "api_client = <petstore_api_client.petstore_api_client.PetstoreApiClient object at 0x734c9c2a7140>\n\n    @allure.title(\"Получение данных о питомце по невалидному id за границами валидации\")\n    def test_get_pet_by_invalid_id(api_client):\n        response = api_client.get_pet_by_pet_id(pet_id=INVALID_ID_VALUE)\n>       assert response.status_code == 400\nE       assert 404 == 400\nE        +  where 404 = <Response [404]>.status_code\n\ntests/test_api_pets.py:79: AssertionError"}, "start": 1724871077763, "stop": 1724871078302, "uuid": "c36be60d-070c-418b-b187-c0601613965d", "historyId": "c6659c727586a96507ce717231dfa22a", "testCaseId": "c6659c727586a96507ce717231dfa22a", "fullName": "tests.test_api_pets#test_get_pet_by_invalid_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_pets"}, {"name": "host", "value": "ASUSLaptop-X509FA"}, {"name": "thread", "value": "106676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_pets"}]}